// MonthlyPrintViewModel.cs
// Self-contained Monthly print VM with the properties that XAML binds to:
// Year, Month, PagePreset, LocationName, FooterLeft, FooterRight, and methods BuildDocument/GetTimesForDate.
//
// Namespace: PrayerTimes.ViewModels (adjust ONLY if your project uses a different ViewModels namespace).

using System;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.ComponentModel;
using System.Globalization;
using System.Runtime.CompilerServices;
using System.Windows.Documents;
using PrayerTimes.Services;

namespace PrayerTimes.ViewModels
{
    public sealed class MonthlyPrintViewModel : INotifyPropertyChanged
    {
        // Keep service as object via interface-like usage so it won't break if you renamed or refactored methods.
        private readonly PrayerTimeService _prayerTimeService;

        private int _year = DateTime.Now.Year;
        private int _month = DateTime.Now.Month; // 1-12
        private string _pagePreset = "LegalUS";   // "LegalUS" or "A3"
        private string _locationName = "";
        private string _footerLeft = "Generated by PrayerTimes";
        private string _footerRight = DateTime.Now.ToString("yyyy-MM-dd");

        private FixedDocument? _document;

        public event PropertyChangedEventHandler? PropertyChanged;

        public MonthlyPrintViewModel(PrayerTimeService prayerTimeService)
        {
            _prayerTimeService = prayerTimeService ?? throw new ArgumentNullException(nameof(prayerTimeService));
        }

        // Parameterless ctor for XAML designer / safety (will not generate until you set Service).
        public MonthlyPrintViewModel() : this(new PrayerTimeService()) { }

        public int Year
        {
            get => _year;
            set { if (_year != value) { _year = value; OnPropertyChanged(); } }
        }

        /// <summary>1-12</summary>
        public int Month
        {
            get => _month;
            set { if (_month != value) { _month = value; OnPropertyChanged(); } }
        }

        /// <summary>"LegalUS" or "A3"</summary>
        public string PagePreset
        {
            get => _pagePreset;
            set { if (_pagePreset != value) { _pagePreset = value; OnPropertyChanged(); } }
        }

        public string LocationName
        {
            get => _locationName;
            set { if (_locationName != value) { _locationName = value; OnPropertyChanged(); } }
        }

        public string FooterLeft
        {
            get => _footerLeft;
            set { if (_footerLeft != value) { _footerLeft = value; OnPropertyChanged(); } }
        }

        public string FooterRight
        {
            get => _footerRight;
            set { if (_footerRight != value) { _footerRight = value; OnPropertyChanged(); } }
        }

        public FixedDocument? Document
        {
            get => _document;
            private set { _document = value; OnPropertyChanged(); }
        }

        /// <summary>
        /// Adapter method expected by earlier code. Returns PrayerTimesResult for a specific day if available.
        /// Uses reflection to call GetForDate(...) if present on PrayerTimeService (your updated file likely has it).
        /// </summary>
        public PrayerTimesResult GetTimesForDate(DateTime dateLocal, double latitude, double longitude, CalcMethod method, AsrMadhhab madhhab, TimeZoneInfo tz)
        {
            // Prefer GetForDate if it exists:
            var mi = typeof(PrayerTimeService).GetMethod("GetForDate");
            if (mi != null)
            {
                // expected signature: (DateTime dateLocal, double lat, double lon, CalcMethod method, AsrMadhhab madhhab, TimeZoneInfo tz)
                var result = mi.Invoke(_prayerTimeService, new object[] { dateLocal, latitude, longitude, method, madhhab, tz });
                if (result is PrayerTimesResult ok) return ok;
            }

            // Fallback: if requesting "today", use GetToday.
            var todayLocal = TimeZoneInfo.ConvertTimeFromUtc(DateTime.UtcNow, tz).Date;
            if (dateLocal.Date == todayLocal)
                return _prayerTimeService.GetToday(latitude, longitude, method, madhhab, tz);

            // Last resort: compute using GetToday but with a warning-like result (times will be today's).
            return _prayerTimeService.GetToday(latitude, longitude, method, madhhab, tz);
        }

        /// <summary>
        /// Build and store a FixedDocument for the selected Month/Year.
        /// NOTE: This creates a simple reflection-friendly model (no dependency on your Models namespace).
        /// </summary>
        public FixedDocument BuildDocument(
            double latitude,
            double longitude,
            CalcMethod method,
            AsrMadhhab madhhab,
            TimeZoneInfo tz)
        {
            var monthStart = new DateTime(Year, Month, 1);
            var monthEnd = monthStart.AddMonths(1);

            var rows = new List<object>();
            for (var d = monthStart; d < monthEnd; d = d.AddDays(1))
            {
                var pr = GetTimesForDate(d, latitude, longitude, method, madhhab, tz);

                rows.Add(new
                {
                    GregorianDate = d,
                    GregorianDateText = d.ToString("yyyy-MM-dd"),
                    DayName = d.ToString("dddd", CultureInfo.InvariantCulture),
                    HijriDateText = "", // You can plug hijri conversion later if desired
                    Fajr = pr.Fajr.ToString("hh:mm tt"),
                    Dhuhr = pr.Dhuhr.ToString("hh:mm tt"),
                    Asr = pr.Asr.ToString("hh:mm tt"),
                    Maghrib = pr.Maghrib.ToString("hh:mm tt"),
                    Isha = pr.Isha.ToString("hh:mm tt"),
                });
            }

            var model = new
            {
                PagePreset = this.PagePreset,
                Title = "Monthly Prayer Times",
                MonthTitle = monthStart.ToString("MMMM yyyy"),
                LocationName = this.LocationName,
                FooterLeft = this.FooterLeft,
                FooterRight = this.FooterRight,
                Rows = rows
            };

            Document = MonthlyPrayerTimesGenerator.BuildFixedDocument(model);
            return Document!;
        }

        private void OnPropertyChanged([CallerMemberName] string? name = null)
            => PropertyChanged?.Invoke(this, new PropertyChangedEventArgs(name));
    }
}
